export enum Category {
  income = 'income',
  utility = 'utility',
  rent = 'rent',
  debt = 'debt',
  food = 'food',
  tech = 'tech',
  entertainment = 'entertainment',
  gas = 'gas',
  insurance = 'insurance',
  medical = 'medical',
  house = 'house',
  travel = 'travel',
  misc = 'misc',
}
